blank_issues_enabled: false
contact_links:
  - name: I need support
    url: https://github.com/alexdelprete/ha-sinapsi-alfa/discussions/new?category=support
    about: Questions? Problems? Get help here
  - name: Feature request
    url: https://github.com/alexdelprete/ha-sinapsi-alfa/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Anything else
    url: https://github.com/alexdelprete/ha-sinapsi-alfa/discussions/new?category=general
    about: If it's something else or you're not sure, open a discussion